// Generated by gencpp from file client_action/my_service.msg
// DO NOT EDIT!


#ifndef CLIENT_ACTION_MESSAGE_MY_SERVICE_H
#define CLIENT_ACTION_MESSAGE_MY_SERVICE_H

#include <ros/service_traits.h>


#include <client_action/my_serviceRequest.h>
#include <client_action/my_serviceResponse.h>


namespace client_action
{

struct my_service
{

typedef my_serviceRequest Request;
typedef my_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct my_service
} // namespace client_action


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::client_action::my_service > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::client_action::my_service&) { return value(); }
};

template<>
struct DataType< ::client_action::my_service > {
  static const char* value()
  {
    return "client_action/my_service";
  }

  static const char* value(const ::client_action::my_service&) { return value(); }
};


// service_traits::MD5Sum< ::client_action::my_serviceRequest> should match
// service_traits::MD5Sum< ::client_action::my_service >
template<>
struct MD5Sum< ::client_action::my_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::client_action::my_service >::value();
  }
  static const char* value(const ::client_action::my_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::client_action::my_serviceRequest> should match
// service_traits::DataType< ::client_action::my_service >
template<>
struct DataType< ::client_action::my_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::client_action::my_service >::value();
  }
  static const char* value(const ::client_action::my_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::client_action::my_serviceResponse> should match
// service_traits::MD5Sum< ::client_action::my_service >
template<>
struct MD5Sum< ::client_action::my_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::client_action::my_service >::value();
  }
  static const char* value(const ::client_action::my_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::client_action::my_serviceResponse> should match
// service_traits::DataType< ::client_action::my_service >
template<>
struct DataType< ::client_action::my_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::client_action::my_service >::value();
  }
  static const char* value(const ::client_action::my_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIENT_ACTION_MESSAGE_MY_SERVICE_H
