// Generated by gencpp from file client_action/my_serviceResponse.msg
// DO NOT EDIT!


#ifndef CLIENT_ACTION_MESSAGE_MY_SERVICERESPONSE_H
#define CLIENT_ACTION_MESSAGE_MY_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace client_action
{
template <class ContainerAllocator>
struct my_serviceResponse_
{
  typedef my_serviceResponse_<ContainerAllocator> Type;

  my_serviceResponse_()
    {
    }
  my_serviceResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::client_action::my_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::client_action::my_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct my_serviceResponse_

typedef ::client_action::my_serviceResponse_<std::allocator<void> > my_serviceResponse;

typedef boost::shared_ptr< ::client_action::my_serviceResponse > my_serviceResponsePtr;
typedef boost::shared_ptr< ::client_action::my_serviceResponse const> my_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::client_action::my_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::client_action::my_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace client_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::client_action::my_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::client_action::my_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client_action::my_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::client_action::my_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client_action::my_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::client_action::my_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::client_action::my_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::client_action::my_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::client_action::my_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "client_action/my_serviceResponse";
  }

  static const char* value(const ::client_action::my_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::client_action::my_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::client_action::my_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::client_action::my_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::client_action::my_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::client_action::my_serviceResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CLIENT_ACTION_MESSAGE_MY_SERVICERESPONSE_H
